name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test (CPU & CUDA)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [cpu, cuda]
    env:
      IMAGE: ghcr.io/${{ github.repository }}/edge-serve:${{ github.sha }}-${{ matrix.variant }}
    steps:
      - uses: actions/checkout@v4

      # Docker buildx = multi-platform + cache
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      # Optional (push to GHCR for cache-reuse / Helm)
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: runtime
          tags: ${{ env.IMAGE }}
          build-args: |
            VARIANT=${{ matrix.variant }}
          load: true

      - name: Run pytest + coverage inside container
        run: |
          docker run --rm -v $PWD:/workspace $IMAGE \
            bash -c "pytest -q --cov=wnba --cov-report=xml:/workspace/coverage.xml"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}